services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: npx nodemon --legacy-watch server.js

  frontend:
    build: ./frontend/train
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/train:/app
      - /app/node_modules
    command: npm run dev -- --host 0.0.0.0
